id: "eau"
version: "1.0"
errorOnUnknownProfile: "true"
anyExtensionsAllowed: "false"
ignoredCodeSystems:
  - "http://fhir.de/CodeSystem/dimdi/icd-10-gm"
  - "http://fhir.de/CodeSystem/bfarm/icd-10-gm"

dependencyLists:
  # https://simplifier.net/eRezept/~packages
  kbv.ita.eau.1.0.2:
    packages:
      - "kbv.ita.eau-1.0.2.tgz"
      - "gematik.kbv.eau.sfhir.cs.vs-1.0.0.tgz"
      - "kbv.ita.for-1.0.3.tgz"
      - "kbv.basis-1.1.3.tgz"
      - "de.basisprofil.r4-0.9.13.tgz"
    validFrom: "2021-07-01"
    validTill: "2023-12-31" # Übergangszeitraum, cf. https://update.kbv.de/ita-update/DigitaleMuster/eAU/KBV_ITA_VGEX_Technische_Anlage_eAU.pdf

  kbv.ita.eau.1.1.0:
    packages:
      - "kbv.ita.eau-1.1.1.tgz"
      - "gematik.kbv.eau.sfhir.cs.vs-1.1.0.tgz"
      - "kbv.ita.for-1.1.0.tgz"
      - "kbv.basis-1.3.0.tgz"
      - "de.basisprofil.r4-1.3.2.tgz"
    validFrom: "2023-07-01"
    validTill: "2024-09-30"

  kbv.ita.eau.1.1.0-from-10-2024:
    packages:
      - "kbv.ita.eau-1.1.1.tgz"
      - "gematik.kbv.eau.sfhir.cs.vs-1.2.0.tgz" # Update KBV_CS_SFHIR_KBV_DMP --> 1.06, KBV_CS_SFHIR_KBV_PERSONENGRUPPE --> 1.03
      - "kbv.ita.for-1.1.0.tgz"
      - "kbv.basis-1.3.0.tgz"
      - "de.basisprofil.r4-1.3.2.tgz"
    validFrom: "2024-10-01"

  kbv.ita.eau.1.2.0:
    packages:
      - "kbv.ita.eau-1.2.0.tgz"
      - "gematik.kbv.eau.sfhir.cs.vs-1.2.0.tgz"
      - "kbv.ita.for-1.2.0.tgz"
      - "kbv.basis-1.7.0.tgz"
      - "de.basisprofil.r4-1.5.2.tgz"
    validFrom: "2025-10-01"

supportedProfiles:
  "http://hl7.org/fhir/StructureDefinition/Bundle":
    profileVersions:
      0.0.0:
        dependencyLists:
          - "kbv.ita.eau.1.0.2"

  "https://fhir.kbv.de/StructureDefinition/KBV_PR_EAU_Bundle":
    profileVersions:
      1.1.0:
        dependencyLists:
          - "kbv.ita.eau.1.1.0"
          - "kbv.ita.eau.1.1.0-from-10-2024"
        creationDateLocator: "Bundle.entry.resource.where(meta.profile.contains('KBV_PR_EAU_Composition')).date"
      1.0.2:
        dependencyLists:
          - "kbv.ita.eau.1.0.2"
        creationDateLocator: "Bundle.entry.resource.where(meta.profile.contains('KBV_PR_EAU_Composition')).date"
      1.2:
        dependencyLists:
          - "kbv.ita.eau.1.2.0"
        creationDateLocator: "Bundle.entry.resource.where(meta.profile.contains('KBV_PR_EAU_Composition')).date"

  "https://fhir.kbv.de/StructureDefinition/KBV_PR_EAU_Composition":
    profileVersions:
      1.1.0:
        dependencyLists:
          - "kbv.ita.eau.1.1.0"
          - "kbv.ita.eau.1.1.0-from-10-2024"
        creationDateLocator: "date"
      1.0.2:
        dependencyLists:
          - "kbv.ita.eau.1.0.2"
        creationDateLocator: "date"
      1.2:
        dependencyLists:
          - "kbv.ita.eau.1.2.0"
        creationDateLocator: "date"

  "https://fhir.kbv.de/StructureDefinition/KBV_PR_EAU_Condition_AU":
    profileVersions:
      1.1.0:
        dependencyLists:
          - "kbv.ita.eau.1.1.0"
          - "kbv.ita.eau.1.1.0-from-10-2024"
      1.0.2:
        dependencyLists:
          - "kbv.ita.eau.1.0.2"
      1.2:
        dependencyLists:
          - "kbv.ita.eau.1.2.0"

  "https://fhir.kbv.de/StructureDefinition/KBV_PR_EAU_Condition_ICD":
    profileVersions:
      1.1.0:
        dependencyLists:
          - "kbv.ita.eau.1.1.0"
          - "kbv.ita.eau.1.1.0-from-10-2024"
      1.0.2:
        dependencyLists:
          - "kbv.ita.eau.1.0.2"
      1.2:
        dependencyLists:
          - "kbv.ita.eau.1.2.0"

  "https://fhir.kbv.de/StructureDefinition/KBV_PR_EAU_Condition_Text":
    profileVersions:
      1.1.0:
        dependencyLists:
          - "kbv.ita.eau.1.1.0"
          - "kbv.ita.eau.1.1.0-from-10-2024"
      1.0.2:
        dependencyLists:
          - "kbv.ita.eau.1.0.2"
      1.2:
        dependencyLists:
          - "kbv.ita.eau.1.2.0"

  "https://fhir.kbv.de/StructureDefinition/KBV_PR_EAU_ServiceRequest_steps":
    profileVersions:
      1.1.0:
        dependencyLists:
          - "kbv.ita.eau.1.1.0"
          - "kbv.ita.eau.1.1.0-from-10-2024"
      1.0.2:
        dependencyLists:
          - "kbv.ita.eau.1.0.2"
      1.2:
        dependencyLists:
          - "kbv.ita.eau.1.2.0"

  "https://fhir.kbv.de/StructureDefinition/KBV_PR_EAU_Storno":
    profileVersions:
      1.1.0:
        dependencyLists:
          - "kbv.ita.eau.1.1.0"
          - "kbv.ita.eau.1.1.0-from-10-2024"
      1.0.2:
        dependencyLists:
          - "kbv.ita.eau.1.0.2"
      1.2:
        dependencyLists:
          - "kbv.ita.eau.1.2.0"

  "https://fhir.kbv.de/StructureDefinition/KBV_PR_EAU_Storno_Bundle":
    profileVersions:
      1.1.0:
        dependencyLists:
          - "kbv.ita.eau.1.1.0"
          - "kbv.ita.eau.1.1.0-from-10-2024"
        creationDateLocator: "Bundle.entry.resource.where(meta.profile.contains('KBV_PR_EAU_Storno_Composition')).date"
      1.0.2:
        dependencyLists:
          - "kbv.ita.eau.1.0.2"
        creationDateLocator: "Bundle.entry.resource.where(meta.profile.contains('KBV_PR_EAU_Storno_Composition')).date"
      1.2:
        dependencyLists:
          - "kbv.ita.eau.1.2.0"
        creationDateLocator: "Bundle.entry.resource.where(meta.profile.contains('KBV_PR_EAU_Storno_Composition')).date"

  "https://fhir.kbv.de/StructureDefinition/KBV_PR_EAU_Storno_Composition":
    profileVersions:
      1.1.0:
        dependencyLists:
          - "kbv.ita.eau.1.1.0"
          - "kbv.ita.eau.1.1.0-from-10-2024"
        creationDateLocator: "date"
      1.0.2:
        dependencyLists:
          - "kbv.ita.eau.1.0.2"
        creationDateLocator: "date"
      1.2:
        dependencyLists:
          - "kbv.ita.eau.1.2.0"
        creationDateLocator: "date"


  "https://fhir.kbv.de/StructureDefinition/KBV_PR_EAU_health_insurance_Practitioner":
    profileVersions:
      1.1.0:
        dependencyLists:
          - "kbv.ita.eau.1.1.0"
          - "kbv.ita.eau.1.1.0-from-10-2024"
      1.0.2:
        dependencyLists:
          - "kbv.ita.eau.1.0.2"
      1.2:
        dependencyLists:
          - "kbv.ita.eau.1.2.0"