id: "erpta7"
version: "0.4"

dependencyLists:
  de.gkvsv.erezeptabrechnungsdaten.1.3.4:
    packages:
      - "de.gkvsv.erezeptabrechnungsdaten-1.3.4.tgz"
      - "de.abda.erezeptabgabedatenbasis-1.3.1.tgz"
      - "gematik.kbv.sfhir.cs.vs-1.2.0.tgz"
      - "de.basisprofil.r4-1.3.2.tgz"
    validFrom: "2023-07-01"
    validTill: "2024-10-31"

  de.gkvsv.erezeptabrechnungsdaten.1.4.2:
    packages:
      - "de.gkvsv.erezeptabrechnungsdaten-1.4.2.tgz"
      - "de.abda.erezeptabgabedatenbasis-1.4.0.tgz"
      - "de.basisprofil.r4-1.3.2.tgz"
    validFrom: "2024-11-01"
    validTill: "2025-09-30"

  de.gkvsv.erezeptabrechnungsdaten.1.5.1:
    packages:
      - "de.gkvsv.erezeptabrechnungsdaten-1.5.1.tgz"
      - "de.abda.erezeptabgabedatenbasis-1.5.0.tgz"
      - "de.basisprofil.r4-1.5.2.tgz"
    validFrom: "2025-10-01"

supportedProfiles:
  "https://fhir.gkvsv.de/StructureDefinition/GKVSV_PR_TA7_Rechnung_Bundle":
    profileVersions:
      1.3:
        dependencyLists:
          - "de.gkvsv.erezeptabrechnungsdaten.1.3.4"
        creationDateLocator: "Bundle.entry.resource.where(meta.profile.contains('GKVSV_PR_TA7_Rechnung_Composition')).date"
      1.4:
        dependencyLists:
          - "de.gkvsv.erezeptabrechnungsdaten.1.4.2"
        creationDateLocator: "Bundle.entry.resource.where(meta.profile.contains('GKVSV_PR_TA7_Rechnung_Composition')).date"
      1.5:
        dependencyLists:
          - "de.gkvsv.erezeptabrechnungsdaten.1.5.1"
        creationDateLocator: "Bundle.entry.resource.where(meta.profile.contains('GKVSV_PR_TA7_Rechnung_Composition')).date"