id: "erpta7"
version: "0.1"

dependencyLists:
  de.gkvsv.erezeptabrechnungsdaten.1.3.0:
    packages:
      - "de.gkvsv.erezeptabrechnungsdaten-1.3.0.tgz"
      - "de.abda.erezeptabgabedatenbasis-1.3.1.tgz"
      - "gematik.kbv.sfhir.cs.vs-1.2.0.tgz"
      - "de.basisprofil.r4-1.3.2.tgz"
    validFrom: "2023-07-01"

supportedProfiles:
  "https://fhir.gkvsv.de/StructureDefinition/GKVSV_PR_TA7_Rechnung_Bundle":
    profileVersions:
      1.3:
        dependencyLists:
          - "de.gkvsv.erezeptabrechnungsdaten.1.3.0"
        creationDateLocator: "Bundle.entry.resource.where(meta.profile.contains('GKVSV_PR_TA7_Rechnung_Composition')).date"